#!/usr/bin/env racket
;; -*- mode: racket -*-

#|
Creates the Gyoko Shoujo site from the images and the directory structure
in the content directory. The site is then committed to the gh-pages
branch.

The content directory structure provides the primary input through the use
of images and optional markdown files. Here is an example set of
content:

    content/
        index.md
        toc.md
        1 - The First Chapter/
            1 - The page title.png
            1 - The page title.md
            2.png
            3 - A new page title.png
        2 - Chapter the Second/
            1.png
            2.png
            3.png
            3.md
    blog/
        Article Title.md
        Another Article.md
    static/
        header.png
        footer.png

This would output a site that looks like this:

    index.html
    toc.html
    the-first-chapter/
        index.html
        page-1.html
        page-2.html
        page-3.html
    chapter-the-second/
        index.html
        page-1.html
        page-2.html
        page-3.html
    blog/
        index.html
        article-title.html
        another-article.html
    static/
        the-first-chapter/
            page-images/
                page-1.png
                page-2.png
                page-3.png
            page-thumbnails/
                page-1.png
                page-2.png
                page-3.png
        chapter-the-second
            page-images/
                page-1.png
                page-2.png
                page-3.png
            page-thumbnails/
                page-1.png
                page-2.png
                page-3.png

The html is generated from templates in the template directory. The following
templates are used:

content.jinja:    Generic template for markdown files in the content directory.
<name>.jinja:     Page-specific template for a file in the content directory.
                  In this examples, "index.jinja" could be used for index.md.
toc.jinja:        Renders the table of contents.
chapter.jinja:    Renders thumbnails of a chapter's pages.
page.jinja:       Renders a page (one image) from a chapter.
blog-index.jinja: Renders the blog index.
glog-page.jinja:  Renders a single article for the blog.

Images, CSS files and the like belong in the static directory and will be
copied directly to the output's static directory.
|#

#lang racket/base

(require racket/cmdline
         racket/format)

(require "gyoko/git.rkt"
         "gyoko/logger.rkt"
         "gyoko/site.rkt")

(define branch    (make-parameter "master"))
(define remote    (make-parameter "origin"))
(define commit?   (make-parameter #t))
(define push?     (make-parameter #t))

(command-line #:program "build-site"
              #:once-each
              [("--branch")   b  "Branch to commit to <master>"    (branch b)  ]
              [("--remote")   r  "Remote repo to push to <origin>" (remote r)  ]
              [("--no-push")     "Don't push changes"              (push? #f)  ]
              [("--no-commit")   "Don't commit changes" (push? #f) (commit? #f)]
              #:once-any
              [("-v" "--verbose") "Be more verbose"  (log-level 1)]
              [("-d" "--debug")   "Be extra verbose" (log-level 2)])

(local-git (find-git-base (find-system-path 'run-file)))
(build-git (build-path (find-system-path 'temp-dir)
                       (string-append "gyo" (~a (current-seconds)))))
(site-content-path (local-git))
(site-output-path (build-git))

(debug "Using local git repo in: ~s~n" (local-git))
(debug "Generating site in: ~s~n" (site-output-path))

(checkout-site (branch))
(generate-site)
(when (commit?)
  (commit-site))
