#!/usr/local/bin/python3.4

from datetime import datetime
import functools
import os
import shutil
import signal
import subprocess
import sys

import requests

CURRENT_CHAPTER_NUM = '7'
CURRENT_CHAPTER = '%s - Will To Live' % CURRENT_CHAPTER_NUM
DROPBOX_FOLDER = r'/Users/travis/Dropbox/Gyoko Shoujo!'
DROPBOX_PREFIX = 'WtL'

src_dir = os.path.realpath(
    os.path.join(os.path.dirname(__file__), '..'))
page_dir = os.path.join(src_dir, 'content', CURRENT_CHAPTER)

def text_message(msg):
    text_url = 'http://www.onlinetextmessage.com/send.php'
    body = {
        'code' : '',
        'number' : '8017557362',
        'from' : 'me@example.com',
        'remember' : 'n',
        'subject' : 'GS Publishing Error',
        'carrier' : '41',
        'quicktext' : '',
        'message' : msg,
        's' : 'Send Message'
    }
    res = requests.post(text_url, data=body)
    if res.status_code != 200:
        print('Unable to send message:\n%s\nResponse: %s' %
              (msg, res.status_code), file=sys.stderr)
        sys.exit(-1)

def send_error(short_msg, full_msg=None):
    if not full_msg:
        full_msg = short_msg
    print('%s (%i) - Error publishing page:\n%s' %
          (datetime.isoformat(datetime.now()), os.getpid(), full_msg),
          file=sys.stderr)
    text_message(short_msg)
    sys.exit(-1)


def find_last_page():
    '''Finds the last published page number in this chapter. New chapters
    must still be manually published, so this will raise an error if there
    isn't at least one page.'''
    cur_page = 0
    for fname in os.listdir(page_dir):
        base, _ = os.path.splitext(fname)
        try:
            this_page = int(base)
            if this_page > cur_page:
                cur_page = this_page
        except ValueError:
            pass
    return cur_page

def make_page_path(page_num):
    '''Returns the fully qualified path (including suffix) for the page
    with the given number.'''
    return os.path.join(page_dir, '%i.png' % page_num)

def run_cmd(args, expected_return=0, check_return=True):
    try:
        # os.chdir(src_dir)
        # cmd = ' '.join((s if ' ' not in s else '"%s"' % s for s in args))
        # ret_val = 0
        # ret_val = os.system(cmd)
        # ret_val = subprocess.call(args, cwd=src_dir, timeout=timeout)
        proc = subprocess.Popen(
            args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            cwd=src_dir, bufsize=1, universal_newlines=True)
        while True:
            l = proc.stdout.readline()
            if not l:
                break
            print(l, end='', flush=True)
        ret_val = proc.poll()
        if check_return and ret_val != expected_return:
            send_error('%s exited with %s' % (args[0], str(ret_val)),
                       'Sub-command failed with %s:\n Command: "%s"' %
                       (ret_val, ' '.join(args)))
    except subprocess.TimeoutExpired:
        send_error('%s timed out!' % (args[0]),
                   'Sub-command timed out after %i seconds:\n Command: "%s"' %
                   (timeout, ' '.join(args)))

def copy_page(page_num):
    src_name = '%s-%i.png' % (DROPBOX_PREFIX, page_num)
    src = os.path.join(DROPBOX_FOLDER, src_name)
    dest = make_page_path(page_num)
    if not os.path.exists(src):
        send_error('Unable to find source file: %s' % src)
    shutil.copyfile(src, dest)

def git_add_page(page_num):
    run_cmd(['git', 'add', make_page_path(page_num)])

def git_commit_page(page_num):
    run_cmd(['git', 'commit', '-m',
             'chapter %s page %i' % (CURRENT_CHAPTER_NUM, page_num)])

def build_site():
    run_cmd(['./build-site', '-d'])

def signal_handler(signal_num, exit, *args):
    print('Signal raised: ' + str(signal_num), file=sys.stderr)
    if exit:
        raise SystemExit(signal_num + 128)

def setup_signals():
    for sig in (signal.SIGHUP, signal.SIGINT, signal.SIGQUIT,
                signal.SIGALRM, signal.SIGTERM):
        signal.signal(sig, functools.partial(signal_handler, sig, True))
    for sig in (signal.SIGCHLD,):
        signal.signal(sig, functools.partial(signal_handler, sig, False))

if __name__ == '__main__':
    try:
        setup_signals()
        page_num = find_last_page() + 1
        copy_page(page_num)
        git_add_page(page_num)
        git_commit_page(page_num)
        build_site()
    except Exception as e:
        import traceback
        send_error('Generic exception: %s' % str(e), traceback.format_exc())
